version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: geomapping
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
