const barangays = [
  "Acedillo",
  "Aguit-itan",
  "Alibaba",
  "Amampacang",
  "Anislag",
  "Awang East (POB.)",
  "Awang West (POB.)",
  "Ba-ay",
  "Bagacay",
  "Bagong Lipunan",
  "Baja",
  "Balud",
  "Bante",
  "Bantian",
  "Basud",
  "Bayo",
  "Begaho",
  "Binaliw",
  "Bontay",
  "Buenavista",
  "Bugtong",
  "Cabacungan",
  "Cabatuan",
  "Cabicahan",
  "Cabugawan",
  "Cacaransan",
  "Cag-anahaw",
  "Cag-anibong",
  "Cagbanayacao",
  "Cagbayang",
  "Cagbilwang",
  "Cagboborac",
  "Caglanipao Sur",
  "Cagmanipes Norte",
  "Cagmanipes Sur",
  "Cagnipa",
  "Cag-olango",
  "Cagsalaosao",
  "Cahumpan",
  "Calocnayan",
  "Cangumaod",
  "Canhumadac",
  "Capacuhan",
  "Capoocan",
  "Carayman",
  "Carmen",
  "Catabunan",
  "Caybago",
  "Central",
  "Cogon",
  "Dagum",
  "Danao I",
  "Danao II",
  "Dawo",
  "De Victoria",
  "Dinabongan",
  "Dinagan",
  "Dinawacan",
  "Esperanza",
  "Gabay",
  "Gadgaran",
  "Gasdo",
  "Geraga-an",
  "Guinbaoyan Norte",
  "Guinbaoyan Sur",
  "Guin-on",
  "Hamorawon",
  "Helino",
  "Hibabngan",
  "Hibatang",
  "Higasaan",
  "Himalandrog",
  "Hugon Rosales",
  "Jacinto",
  "Jimautan",
  "Jose Roño",
  "Kalilihan",
  "Kili-kili",
  "La Paz",
  "Langoyon",
  "Lapaan",
  "Libertad",
  "Limarayon",
  "Longsob",
  "Lonoy",
  "Looc",
  "Mabini I",
  "Mabini II",
  "Macatingog",
  "Mag-ubay",
  "Manguinoo",
  "Malaga",
  "Malajog",
  "Malayog",
  "Malopalo",
  "Mancol",
  "Mantaong",
  "Manuel Barral Sr.",
  "Marcatubig",
  "Matobato",
  "Mawacat",
  "Maybog",
  "Maysalong",
  "Migara",
  "Nabang",
  "Naga",
  "Naguma",
  "Navarro",
  "Nijaga",
  "Obo-ob",
  "Obrero",
  "Olera",
  "Oquendo",
  "Osmeña",
  "Pagbalican",
  "Palanas Cara",
  "Palanogan",
  "Panlayahan",
  "Panonongon",
  "Panoypoy",
  "Patong",
  "Payahan",
  "Peña",
  "Pilar",
  "Pinamorotan",
  "Quezon",
  "Rawis",
  "Rizal I",
  "Rizal II",
  "Roxas I",
  "Roxas II",
  "Saljag (Baut)",
  "Salvacion",
  "San Antonio",
  "San Isidro",
  "San Joaquin",
  "San Jose",
  "San Policarpo",
  "San Rufino",
  "Saputan",
  "Sigo",
  "Sinantan",
  "Sinidman Occ.",
  "Sinidman Or.",
  "Tabawan",
  "Talahiban",
  "Tanval",
  "Tapa-e",
  "Tarabucan",
  "Tigbe",
  "Tinambacan Norte",
  "Tinambacan Sur",
  "Tinaplacan",
  "Tomaliquez",
  "Trinidad",
  "Victory",
  "Villahermosa",
];

export { barangays };
